image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - wpilibsuite.vscode-wpilib@2021.2.1:A4Ra350q6emqbHkLatB/Dg==
    - redhat.java@0.73.0:zlb1d2d/RWALCADFGFpJMg==
    - vscjava.vscode-java-dependency@0.16.0:wWf+IBtGNvKfRuFRdX+Kjw==
    - vscjava.vscode-java-debug@0.30.0:DaEmYtyUCSxaY5vXQG3CJQ==
    - ms-vscode.cpptools@1.1.3:8J7wiDlqJGxnxcM0gJYGEA==