image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview
    
vscode:
  extensions:
    - ms-vscode.cpptools@0.26.2:TkbJMXArQ9iIo9ySZRerdQ==
    - redhat.java@0.55.1:qy2DXX8tZPha11NaQ9gC0w==
    - vscjava.vscode-java-dependency@0.6.0:XkyeyJWk/nK6xEO886ltYg==
    - vscjava.vscode-java-debug@0.24.0:4bjzZag4ZW2bFcv6qiRCEg==
